src/Fdr/AdminBundle/Entity/Manutention.php
<?php

namespace Fdr\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * Manutention
 * @ORM\Table(name="manutention")
 * @ORM\Entity(repositoryClass="Fdr\AdminBundle\Entity\ManutentionRepository")
 */
class Manutention {

    public function __construct() {
        
    }

    /**
     * @ORM\ManyToOne(targetEntity="FeuilleDeRoute",inversedBy="manutentions")
     * @ORM\JoinColumn(nullable=true,onDelete="CASCADE")
     */
    private $feuilleDeRoute;

    /**
     * @var integer
     * @ORM\Column(name="nombreManutentions", type="integer", nullable=true)
     */
    private $nombreManutentions = 0;

    /**
     * @var integer
     * @ORM\Column(name="nombrePrimeNuit", type="integer", nullable=true)
     */
    private $nombrePrimeNuit = 0;

    /**
     * @var integer
     * @ORM\Column(name="nombrePetitDej", type="integer", nullable=true)
     */
    private $nombrePetitDej = 0;
    
    /**
     * @var integer
     *
     * @ORM\Column(name="id",type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="Chauffeur",inversedBy="manutentions")
     * @ORM\JoinColumn(nullable=true,onDelete="SET NULL")
     */
    private $chauffeur;

    /**
     * @ORM\ManyToOne(targetEntity="Manutentionnaire",inversedBy="manutentions")
     * @ORM\JoinColumn(nullable=true,onDelete="SET NULL")
     */
    private $manutentionnaire;

    public function __toString() {
        if($this->getChauffeur()!=null) return " Chauffeur : ".$this->getChauffeur()->getNom ()." ".$this->getChauffeur()->getPrenom()."(".$this->getChauffeur()->getMatricule().")"."[".$this->nombreManutentions."]";
        else if($this->getManutentionnaire()!=null) return " Manutentionnaire : ".$this->getManutentionnaire()->getNom()." ".$this->getManutentionnaire()->getPrenom()."(".$this->getManutentionnaire()->getMatricule().")"."[".$this->nombreManutentions."]";
        else return "";
    }
    
    public function setDisponibilite($etat){
        if ($this->getChauffeur()!=null and $this->getChauffeur()!="")$this->getChauffeur()->setDisponibilite($etat);
        else if ($this->getManutentionnaire()!=null and $this->getManutentionnaire()!="")$this->getManutentionnaire()->setDisponibilite($etat);
    }
    
    public function isChauffeur(){
        return ($this->getChauffeur()!=null and $this->getChauffeur()!="");
    }
    public function isManutentionnaire(){
        return ($this->getManutentionnaire()!=null and $this->getManutentionnaire()!="");
    }
    
    public function isId(){
        if ($this->isChauffeur()){return $this->getChauffeur()->getId();}
        else if($this->isManutentionnaire()){return $this->getManutentionnaire ()->getId();}
        else {return null;}
    }
    public function getDisponibilite(){
        if ($this->isChauffeur()){return $this->getChauffeur()->getDisponibilite();}
        else if($this->isManutentionnaire()){return $this->getManutentionnaire ()->getDisponibilite();}
        else {return null;}
    }

    /**
     * Set nombreManutentions
     *
     * @param integer $nombreManutentions
     * @return Manutention
     */
    public function setNombreManutentions($nombreManutentions) {
        $this->nombreManutentions = $nombreManutentions;

        return $this;
    }

    /**
     * Get nombreManutentions
     *
     * @return integer 
     */
    public function getNombreManutentions() {
        return $this->nombreManutentions;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set feuilleDeRoute
     *
     * @param \Fdr\AdminBundle\Entity\FeuilleDeRoute $feuilleDeRoute
     * @return Manutention
     */
    public function setFeuilleDeRoute(\Fdr\AdminBundle\Entity\FeuilleDeRoute $feuilleDeRoute = null) {
        $this->feuilleDeRoute = $feuilleDeRoute;

        return $this;
    }

    /**
     * Get feuilleDeRoute
     *
     * @return \Fdr\AdminBundle\Entity\FeuilleDeRoute 
     */
    public function getFeuilleDeRoute() {
        return $this->feuilleDeRoute;
    }

    /**
     * Set chauffeur
     *
     * @param \Fdr\AdminBundle\Entity\Chauffeur $chauffeur
     * @return Manutention
     */
    public function setChauffeur(\Fdr\AdminBundle\Entity\Chauffeur $chauffeur = null) {
        $this->chauffeur = $chauffeur;

        return $this;
    }

    /**
     * Get chauffeur
     *
     * @return \Fdr\AdminBundle\Entity\Chauffeur 
     */
    public function getChauffeur() {
        return $this->chauffeur;
    }

    /**
     * Set manutentionnaire
     *
     * @param \Fdr\AdminBundle\Entity\Manutentionnaire $manutentionnaire
     * @return Manutention
     */
    public function setManutentionnaire(\Fdr\AdminBundle\Entity\Manutentionnaire $manutentionnaire = null) {
        $this->manutentionnaire = $manutentionnaire;

        return $this;
    }

    /**
     * Get manutentionnaire
     *
     * @return \Fdr\AdminBundle\Entity\Manutentionnaire 
     */
    public function getManutentionnaire() {
        return $this->manutentionnaire;
    }

    /**
     * Set nombrePrimeNuit
     *
     * @param integer $nombrePrimeNuit
     * @return Manutention
     */
    public function setNombrePrimeNuit($nombrePrimeNuit) {
        $this->nombrePrimeNuit = $nombrePrimeNuit;

        return $this;
    }

    /**
     * Get nombrePrimeNuit
     *
     * @return integer 
     */
    public function getNombrePrimeNuit() {
        return $this->nombrePrimeNuit;
    }


    /**
     * Set nombrePetitDej
     *
     * @param integer $nombrePetitDej
     * @return Manutention
     */
    public function setNombrePetitDej($nombrePetitDej)
    {
        $this->nombrePetitDej = $nombrePetitDej;

        return $this;
    }

    /**
     * Get nombrePetitDej
     *
     * @return integer 
     */
    public function getNombrePetitDej()
    {
        return $this->nombrePetitDej;
    }
}

src/Fdr/AdminBundle/Resources/views/Vehiculee/edit.html.twig
{% extends "FOSUserBundle::layout.html.twig" %}
{% block title %}Vehicule|Edit{% endblock %}
{% block fos_user_content %}
{% block body -%}
<div class="page-header"><h1> Modification d'un Vehicule</h1></div>



{{ form_start(edit_form) }}
<div class="row">
    <span class="alert-danger ">{{ form_errors(edit_form) }}</span>
</div>

<div class="row">

    <div class="span6 offset3">

        <fieldset>
            <legend>Formulaire de modification</legend>

            <div class="row-fluid">
                <div class="span5">{{ form_label(edit_form.numSociete," Num. Société ") }}</div>
{{ form_widget(edit_form.numSociete) }}<span class="alert-danger ">{{ form_errors(edit_form.numSociete) }}</span>
            </div>

            <div class="row-fluid">
                <div class="span5">{{ form_label(edit_form.type," Type ") }}</div>
{{ form_widget(edit_form.type) }}<span class="alert-danger ">{{ form_errors(edit_form.type) }}</span>
            </div>

            <div class="row-fluid">
                <div class="span5">{{ form_label(edit_form.remorque," Remorque ") }}</div>
{{ form_widget(edit_form.remorque) }}<span class="alert-danger ">{{ form_errors(edit_form.remorque) }}</span>
            </div>

            <div class="row-fluid">
                <div class="span5">{{ form_label(edit_form.disponibilite," Disponibilité ") }}</div>
{{ form_widget(edit_form.disponibilite) }}<span class="alert-danger ">{{ form_errors(edit_form.disponibilite) }}</span>
            </div>

            <div class="row-fluid">
                <div class="span5">{{ form_label(edit_form.vidange," Vidange ") }}</div>
{{ form_widget(edit_form.vidange) }}<span class="alert-danger ">{{ form_errors(edit_form.vidange) }}</span>
            </div>

            <div class="row-fluid">
                <div class="span5">{{ form_label(edit_form.compteur," Compteur ") }}</div>
{{ form_widget(edit_form.compteur) }}<span class="alert-danger ">{{ form_errors(edit_form.compteur) }}</span>
            </div>

            <div class="row-fluid">
                <div class="span5">{{ form_label(edit_form.matricule," Matricule ") }}</div>
{{ form_widget(edit_form.matricule) }}<span class="alert-danger ">{{ form_errors(edit_form.matricule) }}</span>
            </div>
            
            <div class="row-fluid">
<div class="span5">{{ form_label(edit_form.dateLancement," Date de Lancement ") }}</div>
{{ form_widget(edit_form.dateLancement) }}<span class="alert-danger ">{{ form_errors(edit_form.dateLancement) }}</span>
</div>
           <br/> 
            <div class="row-fluid">
    <div class="span12 center-block">
{{ form_widget(edit_form.submit) }}
    </div>
            </div>

        </fieldset>

    </div>
</div>
{{ form_end(edit_form) }}
<br/>
{% if role.affVehicule%}
<div class="row-fluid">
    <a  href="{{ path('vehicule') }}" class="pull-right">
        <button class="btn btn-default">Revenir à la liste</button>
    </a>
</div>
{%endif%}
{% endblock %}
{% endblock fos_user_content %}

src/Fdr/AdminBundle/Resources/views/Vehiculee/index.html.twig
{% extends "FOSUserBundle::layout.html.twig" %}
{% block title %}Vehicule|Accueil{% endblock %}
{% block fos_user_content %}
{% block body -%}
<div  class="page-header"> <h1>Liste des vehicules</h1></div>
<div class="row-fluid">
<table class="table-responsive records_list table-bordered table-condensed">
    <thead>
        <tr>
            <th>Code</th>
            <th>Num. Société</th>
            <th>Matricule</th>
            <th>Type</th>
            <th>Remorque</th>
            <th>Dispnibilite</th>
            <th>Vidange(Km.)</th>
            <th>Vidange(s) demandé(s)</th>
            <th>Vidange(s) effectué(s)</th>
            <th>Compteur(Km.)</th>
            <th>Date de Lancement</th>
            
        </tr>
    </thead>
    <tbody>
        {% for entity in pagination %}
        <tr>
            <td>{{ entity.id }}</td>
            <td>{{entity.numSociete|default("-----")}}</td>
            <td>{{ entity.matricule|default("-----") }}</td>
            <td>{{ entity.type|default("-----") }}</td>
            <td>
				{% if entity.remorque %}
                <input type="checkbox" disabled readonly checked />
                {%else %}
                <input type="checkbox" disabled readonly />
                {%endif %}
            </td>
            <td>
                                    {% if entity.disponibilite is not null and entity.disponibilite is defined %}
                <input type="checkbox" disabled readonly checked />
                {%else %}
                <input type="checkbox" disabled readonly />
                {%endif %}
            </td>
            <td>{{ entity.vidange|default("-----") }}</td>
            {%set quotient =0%}
            {%if entity.vidange!=0 %}
            {%set quotient =entity.compteur/entity.vidange %}
            {%endif %}
            <td>{{ quotient|round(0,'floor') }}</td>
            <td>{{ entity.nombreVidange|default("-----") }}</td>
            <td>{{ entity.compteur|default("-----") }}</td>
            <td>{% if entity.dateLancement %}{{ entity.dateLancement|date('d/m/Y') }}{% endif %}</td>
            <td class="col-md-4">
                {% if role.affVehicule%}
                <div class="col-md-2">
                    <a target="_blank" href="{{ path('vehicule_show', { 'id': entity.id }) }}">
                        <button title="Afficher" type="submit">
                            <img id="inputButtonAfficher" title="Afficher" src="{{ asset('bundles/fdradmin/images/apercu.png') }}" />
                        </button>
                    </a> 
                </div>
                
                {%endif%}
                {% if role.upVehicule%}
                <div class="col-md-2">
                    <a target="_blank" href="{{ path('vehicule_edit', { 'id': entity.id }) }}">
                        <button title="Modifier" type="submit">
                            <img id="inputButtonModifier" title="Modifier" src="{{ asset('bundles/fdradmin/images/modifier.png') }}" />
                        </button>
                    </a> 
                </div>
                
                {%endif%}
               {% if role.delVehicule%}
                <div class="col-md-2">
                        {{ form(form[entity.id]) }}
                </div>               
                {%endif%}
                
                {% if role.upVehicule%}
                {% if quotient|round(0,'floor')>entity.nombreVidange|default("-----") %}
                <div class="col-md-2">
                        {{ form(vidange_form[entity.id]) }}
                </div>    
                 {%endif%}
                {%endif%}
            </td>
        </tr>
            {%else%}<tr><td colspan="9">Aucun véhicule n'existe pour le moment </td></tr>
        {% endfor %}
    </tbody>
</table>
</div>
<div class="span12" style="text-align: center">
    <div class="row-fluid">
        <div class="pagination-lg">{{ knp_pagination_render(pagination) }}</div>
    </div>
</div>
<br/>
{% if role.crVehicule%}
<div class="row-fluid">
    <a  href="{{ path('vehicule_new') }}" class="pull-right">
        <button class="btn btn-default">Ajouter une nouvelle entité</button>
    </a>
</div>
    {%endif%}
<script>
    $('* [id="form_supprimer"]').each(function() {
        var c = $(this).parent().parent().parent();
        $(this).confirm({
            title: "<span class='text-danger header-logo'>Confirmation de suppression : <span class='badge help-block' title='Si vous confirmez; cette feuille ne sera plus recupérée'> ( Action irréversible ? )</span></span>",
            text: "<div class='text-danger'>Voulez-vous vraiment supprimer  ? </div>",
            post: true,
            confirm: function(button) {
                button.fadeOut(500).fadeIn(500);
                c.submit();
            },
            cancel: function(button) {
                button.fadeOut(500).fadeIn(500);
                button.preventDefault();
            },
            confirmButton: "Oui, J'en veux",
            cancelButton: "Non, Merci",
            confirmButtonClass: "btn-danger"
        });
    }
    );
    $('* [id="form_vidange"]').each(function() {
        var c = $(this).parent().parent().parent();
        $(this).confirm({
            title: "<span class='text-danger header-logo'>Confirmation de vidange : <span class='badge help-block'> ( Action irréversible ? )</span></span>",
            text: "<div class='text-danger'>Voulez-vous vraiment effectuer le vidange  ? </div>",
            post: true,
            confirm: function(button) {
                button.fadeOut(500).fadeIn(500);
                c.submit();
            },
            cancel: function(button) {
                button.fadeOut(500).fadeIn(500);
                button.preventDefault();
            },
            confirmButton: "Oui, J'en veux",
            cancelButton: "Non, Merci",
            confirmButtonClass: "btn-warning"
        });
    }
    );
</script>

{% endblock %}{% endblock fos_user_content %}

src/Fdr/AdminBundle/Resources/views/Vehiculee/new.html.twig
{% extends "FOSUserBundle::layout.html.twig" %}
{% block title %}Vehicule|New{% endblock %}
{% block fos_user_content %}
{% block body -%}
<div class="page-header"><h1> Ajout d'un Vehicule</h1></div>



{{ form_start(form) }}
<div class="row">
    <span class="alert-danger ">{{ form_errors(form) }}</span>
</div>

<div class="row">

    <div class="span6 offset3">

        <fieldset>
            <legend>Formulaire d'ajout</legend>

            <div class="row-fluid">
                <div class="span5">{{ form_label(form.numSociete," Num. Société ") }}</div>
{{ form_widget(form.numSociete) }}<span class="alert-danger ">{{ form_errors(form.numSociete) }}</span>
            </div>


            <div class="row-fluid">
                <div class="span5">{{ form_label(form.type," Type ") }}</div>
{{ form_widget(form.type) }}<span class="alert-danger ">{{ form_errors(form.type) }}</span>
            </div>

            <div class="row-fluid">
                <div class="span5">{{ form_label(form.remorque," Remorque ") }}</div>
{{ form_widget(form.remorque) }}<span class="alert-danger ">{{ form_errors(form.remorque) }}</span>
            </div>

            <div class="row-fluid">
                <div class="span5">{{ form_label(form.disponibilite," Disponibilité ") }}</div>
{{ form_widget(form.disponibilite) }}<span class="alert-danger ">{{ form_errors(form.disponibilite) }}</span>
            </div>

            <div class="row-fluid">
                <div class="span5">{{ form_label(form.vidange," Vidange ") }}</div>
{{ form_widget(form.vidange) }}<span class="alert-danger ">{{ form_errors(form.vidange) }}</span>
            </div>

            <div class="row-fluid">
                <div class="span5">{{ form_label(form.compteur," Compteur ") }}</div>
{{ form_widget(form.compteur) }}<span class="alert-danger ">{{ form_errors(form.compteur) }}</span>
            </div>

            <div class="row-fluid">
                <div class="span5">{{ form_label(form.matricule," Matricule ") }}</div>
{{ form_widget(form.matricule) }}<span class="alert-danger ">{{ form_errors(form.matricule) }}</span>
            </div>
            
            <div class="row-fluid">
<div class="span5">{{ form_label(form.dateLancement," Date de Lancement ") }}</div>
{{ form_widget(form.dateLancement) }}<span class="alert-danger ">{{ form_errors(form.dateLancement) }}</span>
</div>
<br/>
            <div class="row-fluid">
    <div class="span12 center-block">
{{ form_widget(form.submit) }}
    </div>
            </div>
            
        </fieldset>

    </div>
</div>
{{ form_end(form) }}
<br/>
{% if role.affVehicule%}
<div class="row-fluid">
    <a  href="{{ path('vehicule') }}" class="pull-right">
        <button class="btn btn-default">Revenir à la liste</button>
    </a>
</div>
{%endif%}
{% endblock %}

{% endblock fos_user_content %}

src/Fdr/AdminBundle/Resources/views/Vehiculee/show.html.twig
{% extends "FOSUserBundle::layout.html.twig" %}
{% block title %}Vehicule|Show{% endblock %}
{% block fos_user_content %}
{% block body -%}
<div class="page-header"><h1> Affichage d'un Vehicule</h1></div>



{{ form_start(form) }}
<div class="desactiver-champs">
    <div class="row">
        <span class="alert-danger ">{{ form_errors(form) }}</span>
    </div>

    <div class="row">

        <div class="span6 offset3">

            <fieldset>
                <legend></legend>

                <div class="row-fluid">
                    <div class="span5">{{ form_label(form.id," Identifiant ") }}</div>
{{ form_widget(form.id) }}<span class="alert-danger ">{{ form_errors(form.id) }}</span>
                </div>

                <div class="row-fluid">
                    <div class="span5">{{ form_label(form.numSociete," Num. Société ") }}</div>
{{ form_widget(form.numSociete) }}<span class="alert-danger ">{{ form_errors(form.numSociete) }}</span>
                </div>

                <div class="row-fluid">
                    <div class="span5">{{ form_label(form.type," Type ") }}</div>
{{ form_widget(form.type) }}<span class="alert-danger ">{{ form_errors(form.type) }}</span>
                </div>

                <div class="row-fluid">
                    <div class="span5">{{ form_label(form.remorque," Remorque ") }}</div>
{{ form_widget(form.remorque) }}
                </div>

                <div class="row-fluid">
                    <div class="span5">{{ form_label(form.disponibilite," Disponibilité ") }}</div>
{{ form_widget(form.disponibilite) }}
                </div>

                <div class="row-fluid">
                    <div class="span5">{{ form_label(form.vidange," Vidange ") }}</div>
{{ form_widget(form.vidange) }}
                </div>

                <div class="row-fluid">
                    <div class="span5">{{ form_label(form.compteur," Compteur ") }}</div>
{{ form_widget(form.compteur) }}<span class="alert-danger ">{{ form_errors(form.compteur) }}</span>
                </div>

                <div class="row-fluid">
                    <div class="span5">{{ form_label(form.matricule," Matricule ") }}</div>
{{ form_widget(form.matricule) }}<span class="alert-danger ">{{ form_errors(form.matricule) }}</span>
                </div>
                
                <div class="row-fluid">
<div class="span5">{{ form_label(form.dateLancement," Date de Lancement ") }}</div>
{{ form_widget(form.dateLancement) }}<span class="alert-danger ">{{ form_errors(form.dateLancement) }}</span>
</div>

            </fieldset>

        </div>
    </div>
</div>
{{ form_end(form) }}
<br/>
{% if role.affVehicule%}
<div class="row-fluid">
    <a  href="{{ path('vehicule') }}" class="pull-right">
        <button class="btn btn-default">Revenir à la liste</button>
    </a>
</div>
{%endif%}
{% endblock %}
{% endblock fos_user_content %}